### ISSUE TITLE
Name change needed: mad_ctpsa_complex -> mad_ctpsa_cplx

### ISSUE THREAD

**Issue by DavidSagan** [MethodicalAcceleratorDesign/MAD#204]
Some files in src/libgtpsa have not been updated for the name change mad_ctpsa_complex -> mad_ctpsa_cplx. In particular:
```
src/libgtpsa/gtpsa.f90
src/libgtpsa/gtpsa_ex6.c
src/libgtpsa/gtpsa_ex6.f90
src/libgtpsa/gtpsa_ex7.f90
```

**Comment by ldeniau** [comment]
Thanks for pointing it David!
I cleanup ex7.f90 which was not reflecting the ex7.c but was halfway between ex6.c and ex7.c

**Comment by ldeniau** [comment]
As a side note, I fixed some GTPSA functions (in particular convert) as I was implementing the nonlinear normal form in MAD-NG. In fact, implementing nonlinear normal form validated somehow the second half of the libgtpsa code not used by tracking damaps. I will also soon refactor the damap module of MAD-NG that may lead to some API changes and new functions available like the adjoint operators of Lie algebra.
