### ISSUE TITLE
Curvature effects on straight dipole

### ISSUE THREAD

**Issue by rdemaria** [MethodicalAcceleratorDesign/MAD#408]
Straight dipoles don't have weak focusing (see dipole hamiltonian), so those lines look incorrect

https://github.com/MethodicalAcceleratorDesign/MAD/blob/a67b8af3c2cad09f2d9359ee9ede22767208f538/src/madl_dynmap.mad#L591-L592

**Comment by ldeniau** [comment]
This map is only used by the multipole **element** for compatibility with the thin all-in-one multipole element in MAD-X when translated to PTC ("highly illegal" in PTC, Etienne's wording). So it is not an issue but the responsibility of the user...
